apiVersion: v1
kind: Service
metadata:
  name: flask-app-service     # Name of the service
spec:
  selector:
    app: mytesting            # Label selector to match the pods (should match the labels in your deployment.yaml)
  ports:
    - protocol: TCP
      nodePort: 31005 
      port: 80                 # Port the service will expose
      targetPort: 80           # Port your Flask app is running on inside the pod
  type: NodePort           # Exposes the service externally, use NodePort for local dev environments

